# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

pool:
  vmImage: 'vs2017-win2016'

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'Invoke-WebRequest -Uri "mkdir C:\hotspot; https://github.com/AdoptOpenJDK/openjdk16-binaries/releases/download/jdk-16.0.1%2B9/OpenJDK16U-jdk_x64_linux_hotspot_16.0.1_9.tar.gz" -OutFile C:\hotspot\hotspot.tar.gz'
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '16' 
    jdkArchitectureOption: x64
    jdkSourceOption: 'LocalDirectory'
    jdkFile: 'C:\hotspot\hotspot.tar.gz'
    jdkDestinationDirectory: 'C:\jdk'
    cleanDestinationDirectory: true
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.16'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    goals: 'package'
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: '[xml]$pomXml = Get-Content "pom.xml"; $version = $pomXml.project.version; Write-Host "##vso[task.setvariable variable=version]$version"'
- task: PublishPipelineArtifact@0
  inputs:
    targetPath: 'target/commandhelper-$(version)-full.jar'
    artifactName: 'CommandHelper-$(version)-$(Build.BuildNumber).jar'
