name: CommandHelper
main: com.sk89q.commandhelper.CommandHelperPlugin
version: "${project.version}"
commands:
    repeat:
        description: Repeat the last command
        usage: /<command>
        aliases: .
    alias:
        description: Create an alias
        usage: /<command> <alias>
    delalias:
        description: Remove an alias
        usage: /<command> <name>
    reloadaliases:
        description: Reloads aliases
        usage: /<command>
        aliases: reloadalias
    viewalias:
        description: View all user defined aliases
        usage: /<command>
        aliases: viewaliases
    interpreter:
        description: Puts your chat into interpreter mode
        usage: /<command>
    commandhelper:
        description: Used to gain meta information about CommandHelper
        usage: /<command> <arguments>