name: CommandHelper
main: com.sk89q.commandhelper.CommandHelperPlugin
version: CHVERSIONMACRO
commands:
    commandhelper:
        description: Command helper
        usage: /<command>
        aliases: ch
    repeat:
        description: Repeat the last command
        usage: /<command>
        aliases: .
    alias:
        description: Create an alias
        usage: /<command> <name> <cmd>
    delalias:
        description: Remove an alias
        usage: /<command> <name>
    reloadaliases:
        description: Reloads aliases
        usage: /<command>
    viewalias:
        description: View all user defined aliases
        usage: /<command>
        aliases: viewaliases